### PR TITLE
Support more JWS algorithms

### PR DESCRIPTION
**Pull request by shartte**
This PR adds ECDSA support and uses the hash function derived from the JWT alg header for RSA keys too (i.e. RS384 -> SHA-384).

I tested this with ES256 and RS256.

I suppose this could be improved with a far more explicit mapping from JWS `alg` to the compatible key. The `ES***` alg values for example each reference an exlicit ECDSA curve (`ES256` -> `P-256`, `ES384` -> `P-384`, etc.), which could be checked against the corresponding JWK's curve. 

Regardless, this should work :)

### CODE REVIEW

**Comment by psteniusubi** [comment]
Thanks @shartte. I'll have a look. Do you know of a public OIDC provider doing ES256? I'd like to test this.

**Comment by shartte** [comment]
Hm, sadly not, no. I have not tested with any public providers, just my own.

**Comment by psteniusubi** [comment]
I need to extend my test oidc provider with EC support too so that I can test.

Also I know I have implemented Jose EC support before, in my webauthn project here https://github.com/psteniusubi/webauthn-tester/blob/master/docs/assets/local/modules/Crypto.js. I want to see if there is something I could re-use.

**Comment by psteniusubi** [comment]
Hi @shartte. I modified this to use existing functions from Crypto.js. Also I have run tests with all RS and ES signature algorithms in addition to some negative test cases.

I have not yet added kid logic. I think this tool should always attempt verifying with all keys and then report if there is mismatch with kid in jwt header and kid in jwks.

Thanks anyways for raising this issue!

**Pull request closed without merging**
